[package]
name = "dns-proxy"
version = "0.1.0"
edition = "2021"
authors = ["fakeshadow <24548779@qq.com>"]
description = "simple dns relay proxy"
repository = "https://github.com/fakeshadow/dns-proxy.git"
license = "MIT"
readme = "README.md"

keywords = [
    "dns-proxy",
    "dot",
    "doh"
]

[features]
# feature for DoH proxy.
https = ["xitca-client/http2", "xitca-client/rustls"]
# feature for DoT proxy.
tls = ["rustls", "webpki-roots", "xitca-client", "xitca-io"]

[dependencies]
bpaf = "0.5.7"
futures-core = { version = "0.3", default-features = false, features = ["alloc"] }
tokio = { version = "1", features = ["net", "rt-multi-thread", "sync"] }
tracing = { version = "0.1.36", default-features = false }
tracing-subscriber = { version = "0.3", default-features = false, features = ["env-filter", "fmt"] }

# optional for DoH.
xitca-client = { version = "0.1", default-features = false, optional = true }

# optional for DoT.
rustls = { version = "0.20.6", default-features = false, optional = true }
webpki-roots = { version = "0.22", optional = true }
xitca-io = { version = "0.1", optional = true }

[patch.crates-io]
xitca-client = { git = "https://github.com/HFQR/xitca-web" }
xitca-http = { git = "https://github.com/HFQR/xitca-web" }
xitca-io = { git = "https://github.com/HFQR/xitca-web" }
xitca-service = { git = "https://github.com/HFQR/xitca-web" }
xitca-unsafe-collection = { git = "https://github.com/HFQR/xitca-web" }

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
panic = "abort"
strip = true
