[package]
name = "dns-proxy"
version = "0.1.0"
edition = "2021"
authors = ["fakeshadow <24548779@qq.com>"]
description = "simple dns relay proxy"
repository = "https://github.com/fakeshadow/dns-proxy.git"
license = "MIT"
readme = "README.md"

keywords = [
    "dns-proxy",
    "dot",
    "doh"
]

[features]
# feature for DoH proxy.
https = ["xitca-client/http2", "xitca-client/rustls"]
# feature for DoT proxy.
tls = ["http", "rustls", "tokio/time", "webpki-roots", "xitca-io", "xitca-unsafe-collection"]

[dependencies]
bpaf = "0.7"
futures-core = { version = "0.3", default-features = false, features = ["alloc"] }
tokio = { version = "1.26", features = ["net", "rt-multi-thread", "sync", "time"] }
tracing = { version = "0.1", default-features = false }
tracing-subscriber = { version = "0.3", default-features = false, features = ["env-filter", "fmt"] }

# optional for DoH.
xitca-client = { version = "0.1", default-features = false, optional = true }

# optional for DoT.
http = { version = "0.2.9", optional = true }
rustls = { version = "0.20", default-features = false, features = ["tls12"], optional = true }
webpki-roots = { version = "0.22", optional = true }
xitca-io = { version = "0.1", features = ["runtime"], optional = true }
xitca-unsafe-collection = { version = "0.1", features = ["bytes"], optional = true }

[dev-dependencies]
tokio = { version = "1.26", features = ["macros"] }

[patch.crates-io]
xitca-client = { git = "https://github.com/HFQR/xitca-web", rev = "4b48dd0775f79be5686b32449b27141bb3b6f87f" }
xitca-http = { git = "https://github.com/HFQR/xitca-web", rev = "4b48dd0775f79be5686b32449b27141bb3b6f87f" }
xitca-io = { git = "https://github.com/HFQR/xitca-web", rev = "4b48dd0775f79be5686b32449b27141bb3b6f87f" }
xitca-service = { git = "https://github.com/HFQR/xitca-web", rev = "4b48dd0775f79be5686b32449b27141bb3b6f87f" }
xitca-unsafe-collection = { git = "https://github.com/HFQR/xitca-web", rev = "4b48dd0775f79be5686b32449b27141bb3b6f87f" }

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
panic = "abort"
strip = true
